### ISSUE TITLE
Referral Link Not Working

### ISSUE THREAD

**Issue by Missysleggings** [anujtenani/goaffpro#91]
Unable to gain support via shopify. Hoping for some insight.

Implementation of program seemed problem free. However when new buyers attempt to use a referral link to place an order there is no discount being applied to cart 

Please advise

**Comment by palepaul** [comment]
Hello @Missysleggings, 

Make sure that you have:

1. Assigned a coupon code to the affiliate (so that it can get applied at the checkout). [Guide](https://docs.goaffpro.com/how-tos/assign-coupon-to-affiliate) 

2. Have enabled the "Automatically apply discount" option in the Coupons tab. [Guide](https://docs.goaffpro.com/how-tos/automatically-apply-discount-codes) 

(If enabled, only then the coupon code will get applied at the checkout automatically, when your customers visit your store using an affiliate's referral link)

![Annotation 2020-02-03 171958](https://user-images.githubusercontent.com/42622335/99161634-509c8500-271a-11eb-9c7e-2148a5bc3a46.png)

**Comment by Missysleggings** [comment]
Thank you for the instructions however, these steps are not for our app. I
am looking for support for your other Shopify App called PointsKit. I have
emailed admin@pointskit.com and received no response. I have also emailed
shopify support. No one seems to support your other product. Please advise
as the lack of service channels is beyond frustrating. Thank you.

**Comment by palepaul** [comment]
@Missysleggings I understand, please reach out to our team at admin@goaffpro.com (our team is more active on this email) 

They will assist you at the earliest.

**Comment by anujtenani** [comment]
Closing as not related to GOAFFPRO app
