### ISSUE TITLE
Sync and Tracking Issue (WooCommerce)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#98]
A merchant has raised some issues that he is getting:

1. He says that the products in the collections are not getting synced. (GoAffPro is showing 0 products under the categories, even though there are products assigned under them).

![20201201_164618](https://user-images.githubusercontent.com/42622335/101130755-13952580-362a-11eb-9d0b-77ac90f598c8.jpg)

![20201201_164543(1)](https://user-images.githubusercontent.com/42622335/101130770-198b0680-362a-11eb-8a7f-3505be513404.jpg)

2. The visits do seem to be getting recorded using referral links in the Analytics tab (after the tracking code was added manually), however the sales aren't getting tracked. (Order number 1807 was made with a referral link hasn't gotten recorded in GoAffPro)

(Additional details regarding the issue have sent over the email, for the merchant's privacy)

**Comment by anujtenani** [comment]
#1 - This is fixed in the latest update
#2 - This bug was dependent on #1 -> since the merchant has set the commission to 0% and the collections were not getting loaded, hence the final commission for the order came out to be $0. Since the merchant has UNCHECKED "record nil sales" the sale was also not recorded by the app
